---

image:
  repository: ghcr.io/ministryofjustice/hmpps-snyk-discovery
  tag: xxx
  
generic-prometheus-alerts:
  targetApplication: hmpps-snyk-discovery

snykScanCronJob:
  env:
    SNYK_MAX_WORKERS: "4"
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2Gi"
      memory: "6Gi"
  namespace_secrets:
    hmpps-snyk-discovery:
      SERVICE_CATALOGUE_API_ENDPOINT: "SERVICE_CATALOGUE_API_ENDPOINT"
      SERVICE_CATALOGUE_API_KEY: "SERVICE_CATALOGUE_API_KEY"
      SNYK_TOKEN: "SNYK_TOKEN"
    hmpps-sre-app-slack-bot:
      SLACK_BOT_TOKEN: "SLACK_BOT_TOKEN"
    ghcr-pull-secret:
      GHCR_AUTH_CONFIG: ".dockerconfigjson"
