---
# Per environment values which override defaults in hmpps-snyk-discovery/values.yaml

generic-prometheus-alerts:
  alertSeverity: hmpps-sre-alerts-nonprod

snykScanCronJob:
  enabled: true
  full_scan_schedule: "30 4 * * 1-5"
  incremental_scan_schedule: "00 09 * * 1-5"
  env:
    LOG_LEVEL: info

